/*
  Auto-generated by Spline
*/

import { PerspectiveCamera } from '@react-three/drei'
import { OrbitControls } from '@react-three/drei'
import { Bloom, EffectComposer } from '@react-three/postprocessing'
import useSpline from '@splinetool/r3f-spline'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    'https://prod.spline.design/hKgIWhYvLTAKWApD/scene.splinecode'
  )
  return (
    <>
      <color attach="background" args={['#000000']} />
      <group {...props} dispose={null}>
        <OrbitControls />
        <group name="Text" position={[7.35, -24.45, 63.2]}>
          <mesh
            name="Text 6"
            geometry={nodes['Text 6'].geometry}
            material={materials['Text 6 Material']}
            castShadow
            receiveShadow
            position={[1.71, 800, -65.89]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Text 5"
            geometry={nodes['Text 5'].geometry}
            material={materials['Text 5 Material']}
            castShadow
            receiveShadow
            position={[-6.45, -800, -69.29]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Text 4"
            geometry={nodes['Text 4'].geometry}
            material={materials['Text 4 Material']}
            castShadow
            receiveShadow
            position={[753.08, 26.83, -71.41]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            name="Text 3"
            geometry={nodes['Text 3'].geometry}
            material={materials['Text 3 Material']}
            castShadow
            receiveShadow
            position={[-800, 26.83, -71.41]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            name="Text 2"
            geometry={nodes['Text 2'].geometry}
            material={materials['Text 2 Material']}
            castShadow
            receiveShadow
            position={[-6.24, 30.77, -800]}
          />
          <mesh
            name="Text1"
            geometry={nodes.Text1.geometry}
            material={materials['Text1 Material']}
            castShadow
            receiveShadow
            position={[-10.22, 30.3, 800]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
        </group>
        <group name="Outer Structures" scale={0.12}>
          <mesh
            name="Grid"
            geometry={nodes.Grid.geometry}
            material={materials['Grid Material']}
            castShadow
            receiveShadow
            position={[4.01, 23.61, -3.54]}
            scale={2.61}
          />
          <group name="Outer Pipes">
            <group
              name="Top"
              position={[-2.9, 5650.3, 13.05]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={1}
            >
              <mesh
                name="Ellipse"
                geometry={nodes.Ellipse.geometry}
                material={materials['Ellipse Material']}
                position={[0, 0, -3565.73]}
                scale={1.43}
              />
            </group>
            <group
              name="Bottom"
              position={[-28.37, -5655.09, 13.05]}
              rotation={[Math.PI / 2, 0, Math.PI / 2]}
              scale={1}
            >
              <mesh
                name="Ellipse1"
                geometry={nodes.Ellipse1.geometry}
                material={materials['Ellipse1 Material']}
                position={[0, 0, -3565.73]}
                scale={1.43}
              />
            </group>
            <group
              name="Right"
              position={[-5654.19, 24.38, -31.79]}
              rotation={[0, -Math.PI / 2, 0]}
            >
              <mesh
                name="Ellipse2"
                geometry={nodes.Ellipse2.geometry}
                material={materials['Ellipse2 Material']}
                position={[0, 0, -3565.73]}
                scale={1.43}
              />
            </group>
            <group
              name="Back"
              position={[-12.45, 24.38, -5648.91]}
              rotation={[-Math.PI, 0, -Math.PI]}
            >
              <mesh
                name="Ellipse3"
                geometry={nodes.Ellipse3.geometry}
                material={materials['Untitled Material']}
                position={[0, 0, -3565.73]}
                scale={1.43}
              />
            </group>
            <group
              name="Left"
              position={[5643.57, 24.38, -31.79]}
              rotation={[0, Math.PI / 2, 0]}
            >
              <mesh
                name="Ellipse4"
                geometry={nodes.Ellipse4.geometry}
                material={materials['Ellipse4 Material']}
                position={[0, 0, -3565.73]}
                scale={1.43}
              />
            </group>
            <group name="Forward" position={[-12.45, 24.38, 5647.97]}>
              <mesh
                name="Ellipse5"
                geometry={nodes.Ellipse5.geometry}
                material={materials['Ellipse5 Material']}
                position={[0, 0, -3565.73]}
                scale={1.43}
              />
            </group>
          </group>
          <group name="Outer Box" position={[0, 0, 0]} scale={8.68}>
            <group
              name="Side 1 Instance 4"
              position={[0.15, -240.23, 0.83]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            >
              <mesh
                name="Side 1"
                geometry={nodes['Side 1'].geometry}
                material={materials['']}
                castShadow
                receiveShadow
              >
                <mesh
                  name="Ellipse6"
                  geometry={nodes.Ellipse6.geometry}
                  material={materials['Ellipse6 Material']}
                  visible={false}
                  castShadow
                  receiveShadow
                  position={[0, 0, -13.2]}
                  scale={1.01}
                />
                <mesh
                  name="Rectangle"
                  geometry={nodes.Rectangle.geometry}
                  material={materials['Rectangle Material']}
                  visible={false}
                  castShadow
                  receiveShadow
                />
              </mesh>
            </group>
            <group
              name="Side 1 Instance 3"
              position={[0.15, 240.23, 0.83]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            >
              <mesh
                name="Side 11"
                geometry={nodes['Side 11'].geometry}
                material={materials['']}
                castShadow
                receiveShadow
              >
                <mesh
                  name="Ellipse7"
                  geometry={nodes.Ellipse7.geometry}
                  material={materials['Ellipse7 Material']}
                  visible={false}
                  castShadow
                  receiveShadow
                  position={[0, 0, -13.2]}
                  scale={1.01}
                />
                <mesh
                  name="Rectangle1"
                  geometry={nodes.Rectangle1.geometry}
                  material={materials['Rectangle1 Material']}
                  visible={false}
                  castShadow
                  receiveShadow
                />
              </mesh>
            </group>
            <group
              name="Side 1 Instance 2"
              position={[-239.1, 0.4, -0.18]}
              rotation={[0, Math.PI / 2, 0]}
            >
              <mesh
                name="Side 12"
                geometry={nodes['Side 12'].geometry}
                material={materials['']}
                castShadow
                receiveShadow
              >
                <mesh
                  name="Ellipse8"
                  geometry={nodes.Ellipse8.geometry}
                  material={materials['Ellipse8 Material']}
                  visible={false}
                  castShadow
                  receiveShadow
                  position={[0, 0, -13.2]}
                  scale={1.01}
                />
                <mesh
                  name="Rectangle2"
                  geometry={nodes.Rectangle2.geometry}
                  material={materials['Rectangle2 Material']}
                  visible={false}
                  castShadow
                  receiveShadow
                />
              </mesh>
            </group>
            <group
              name="Side 1 Instance"
              position={[239.1, 0.4, 0]}
              rotation={[0, -Math.PI / 2, 0]}
            >
              <mesh
                name="Side 13"
                geometry={nodes['Side 13'].geometry}
                material={materials['']}
                castShadow
                receiveShadow
              >
                <mesh
                  name="Ellipse9"
                  geometry={nodes.Ellipse9.geometry}
                  material={materials['Ellipse9 Material']}
                  visible={false}
                  castShadow
                  receiveShadow
                  position={[0, 0, -13.2]}
                  scale={1.01}
                />
                <mesh
                  name="Rectangle3"
                  geometry={nodes.Rectangle3.geometry}
                  material={materials['Rectangle3 Material']}
                  visible={false}
                  castShadow
                  receiveShadow
                />
              </mesh>
            </group>
            <group
              name="Side 1 Instance 21"
              position={[0, 0.4, -237.74]}
              rotation={[-Math.PI, 0, -Math.PI]}
            >
              <mesh
                name="Side 14"
                geometry={nodes['Side 14'].geometry}
                material={materials['']}
                castShadow
                receiveShadow
              >
                <mesh
                  name="Ellipse10"
                  geometry={nodes.Ellipse10.geometry}
                  material={materials['Ellipse10 Material']}
                  visible={false}
                  castShadow
                  receiveShadow
                  position={[0, 0, -13.2]}
                  scale={1.01}
                />
                <mesh
                  name="Rectangle4"
                  geometry={nodes.Rectangle4.geometry}
                  material={materials['Rectangle4 Material']}
                  visible={false}
                  castShadow
                  receiveShadow
                />
              </mesh>
            </group>
            <group name="Side 15" position={[-0.55, 0.4, 240.04]}>
              <mesh
                name="Side 16"
                geometry={nodes['Side 16'].geometry}
                material={materials['']}
                castShadow
                receiveShadow
              >
                <mesh
                  name="Ellipse11"
                  geometry={nodes.Ellipse11.geometry}
                  material={materials['Ellipse11 Material']}
                  visible={false}
                  castShadow
                  receiveShadow
                  position={[0, 0, -13.2]}
                  scale={1.01}
                />
                <mesh
                  name="Rectangle5"
                  geometry={nodes.Rectangle5.geometry}
                  material={materials['Rectangle5 Material']}
                  visible={false}
                  castShadow
                  receiveShadow
                />
              </mesh>
            </group>
          </group>
        </group>
        <group name="Avatar Group">
          <group
            name="Avatar Animation"
            position={[2, 6.26, 700.36]}
            scale={0.12}
          >
            <group name="Body" position={[-85.47, -232.96, 0]} scale={6.48}>
              <mesh
                name="Body1"
                geometry={nodes.Body1.geometry}
                material={nodes.Body1.material}
                position={[11.35, -122.84, -24.27]}
                scale={1.22}
              />
            </group>
            <group name="Orb" position={[-11.76, 9, -84.07]} scale={0.04}>
              <mesh
                name="Orb1"
                geometry={nodes.Orb1.geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[0, 0, 0]}
                scale={3.15}
              />
            </group>
          </group>
        </group>
        <PerspectiveCamera
          name="Camera Up"
          makeDefault={false}
          zoom={0.4}
          far={100000}
          near={70}
          fov={45}
          position={[0, 200, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <group
            name="Button.Up (End)"
            position={[0, -187.87, -140.62]}
            scale={0.01}
          >
            <mesh
              name="Text 21"
              geometry={nodes['Text 21'].geometry}
              material={materials['Text 21 Material']}
              castShadow
              receiveShadow
            />
            <mesh
              name="Rectangle6"
              geometry={nodes.Rectangle6.geometry}
              material={materials['Rectangle6 Material']}
              castShadow
              receiveShadow
              position={[0, 0, -0.5]}
            />
          </group>
        </PerspectiveCamera>
        <PerspectiveCamera
          name="Camera Down"
          makeDefault={false}
          zoom={0.4}
          far={100000}
          near={70}
          fov={45}
          position={[0, -200, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <group
            name="Button.Down-To-Up"
            position={[0, -187.87, -140.62]}
            scale={0.01}
          >
            <mesh
              name="Text 22"
              geometry={nodes['Text 22'].geometry}
              material={materials['Text 22 Material']}
              castShadow
              receiveShadow
            />
            <mesh
              name="Rectangle7"
              geometry={nodes.Rectangle7.geometry}
              material={materials['Rectangle7 Material']}
              castShadow
              receiveShadow
              position={[0, 0, -0.5]}
            />
          </group>
        </PerspectiveCamera>
        <PerspectiveCamera
          name="Camera Right"
          makeDefault={false}
          zoom={0.4}
          far={100000}
          near={70}
          fov={45}
          position={[-200, 0, 0]}
          rotation={[0, Math.PI / 2, 0]}
        >
          <group
            name="Button.Right-To-Down"
            position={[0, -187.87, -140.62]}
            scale={0.01}
          >
            <mesh
              name="Text 23"
              geometry={nodes['Text 23'].geometry}
              material={materials['Text 23 Material']}
              castShadow
              receiveShadow
            />
            <mesh
              name="Rectangle8"
              geometry={nodes.Rectangle8.geometry}
              material={materials['Rectangle8 Material']}
              castShadow
              receiveShadow
              position={[0, 0, -0.5]}
            />
          </group>
        </PerspectiveCamera>
        <PerspectiveCamera
          name="Camera Back"
          makeDefault={false}
          zoom={0.4}
          far={100000}
          near={70}
          fov={45}
          position={[0, 0, -200]}
        >
          <group
            name="Button.Back-To-Right"
            position={[0, -187.87, -140.62]}
            scale={0.01}
          >
            <mesh
              name="Text 24"
              geometry={nodes['Text 24'].geometry}
              material={materials['Text 24 Material']}
              castShadow
              receiveShadow
            />
            <mesh
              name="Rectangle9"
              geometry={nodes.Rectangle9.geometry}
              material={materials['Rectangle9 Material']}
              castShadow
              receiveShadow
              position={[0, 0, -0.5]}
            />
          </group>
        </PerspectiveCamera>
        <PerspectiveCamera
          name="Camera Left"
          makeDefault={false}
          zoom={0.4}
          far={100000}
          near={70}
          fov={45}
          position={[200, 0, 0]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <group
            name="Button.Left-To-Back"
            position={[0, -187.87, -140.62]}
            scale={0.01}
          >
            <mesh
              name="Text 25"
              geometry={nodes['Text 25'].geometry}
              material={materials['Text 25 Material']}
              castShadow
              receiveShadow
            />
            <mesh
              name="Rectangle10"
              geometry={nodes.Rectangle10.geometry}
              material={materials['Rectangle10 Material']}
              castShadow
              receiveShadow
              position={[0, 0, -0.5]}
            />
          </group>
        </PerspectiveCamera>
        <PerspectiveCamera
          name="Camera Forward"
          makeDefault={false}
          zoom={0.4}
          far={100000}
          near={70}
          fov={45}
          position={[0, 0, 200]}
          rotation={[-Math.PI, 0, -Math.PI]}
        >
          <group
            name="Button.Forward-To-Left"
            position={[0, -187.87, -140.62]}
            scale={0.01}
          >
            <mesh
              name="Text 26"
              geometry={nodes['Text 26'].geometry}
              material={materials['Text 26 Material']}
              castShadow
              receiveShadow
            />
            <mesh
              name="Rectangle11"
              geometry={nodes.Rectangle11.geometry}
              material={materials['Rectangle11 Material']}
              castShadow
              receiveShadow
              position={[0, 0, -0.5]}
            />
          </group>
        </PerspectiveCamera>
        <PerspectiveCamera
          name="Camera"
          makeDefault={true}
          zoom={0.4}
          far={100000}
          near={70}
          fov={45}
          position={[0, 0, 890.37]}
        >
          <group
            name="Button.To-Forward"
            position={[0, -187.87, -140.62]}
            scale={0.01}
          >
            <mesh
              name="Text 27"
              geometry={nodes['Text 27'].geometry}
              material={materials['Text 27 Material']}
              castShadow
              receiveShadow
            />
            <mesh
              name="Rectangle12"
              geometry={nodes.Rectangle12.geometry}
              material={materials['Rectangle12 Material']}
              castShadow
              receiveShadow
              position={[0, 0, -0.5]}
            />
          </group>
          <group name="Button.Start" position={[0.01, -127.89, -230.23]}>
            <group name="Button.Start.Animation">
              <mesh
                name="Text 28"
                geometry={nodes['Text 28'].geometry}
                material={materials['Text 28 Material']}
                castShadow
                receiveShadow
                position={[1.81, 0.96, 6.95]}
              />
              <mesh
                name="Cube 2"
                geometry={nodes['Cube 2'].geometry}
                material={materials['Cube 2 Material']}
                castShadow
                receiveShadow
                position={[0, 0, 6.12]}
                rotation={[Math.PI, 0, -Math.PI]}
                scale={[1.52, 0.68, 0.01]}
              />
            </group>
          </group>
        </PerspectiveCamera>
        <mesh
          name="Audio"
          geometry={nodes.Audio.geometry}
          material={materials['Audio Material']}
          castShadow
          receiveShadow
          scale={0}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} />
      </group>
    </>
  )
}
